services:
  rosws:
    build: .
    container_name: rosws
    ports:
      - "9090:9090" # rosbridge
      - "8888:8888" # jupyter
    environment:
      - ROS_DOMAIN_ID=0
      - TERM=xterm-256color
      - TURTLEBOT3_MODEL=burger
      - WEBOTS_SHARED_FOLDER=$PWD/ws/webots:/home/ros/ros2_ws/webots
      - WEBOTS_HOST=0.0.0.0
    volumes:
      - ./ws:/home/ros/ros2_ws
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
 